Repository apache/dubbo-go, pull requests merged in 2020-08, with the labels that each got.

#702 stack level
  common/logger/log.yml
  go.mod
  go.sum
  registry/nacos/service_discovery_test.go
  test/integrate/dubbo/go-client/log.yml
  test/integrate/dubbo/go-server/log.yml
Labels: bug

#704 Imp: Correct words and format codes
  README.md
  cluster/loadbalance/consistent_hash.go
  cluster/router/condition/router.go
  cluster/router/healthcheck/default_health_check.go
  filter/filter.go
  protocol/dubbo/client.go
  protocol/dubbo/codec.go
  protocol/grpc/server.go
  protocol/invocation/rpcinvocation.go
  protocol/result.go
  registry/etcdv3/service_discovery.go
  registry/nacos/listener.go
  registry/registry.go
  remoting/etcdv3/client.go
  remoting/kubernetes/registry_controller.go
  remoting/zookeeper/client.go
Labels: enhancement

#685 Ftr: add TLS support
  common/constant/key.go
  config/config_loader.go
  config/service_config.go
  config/ssl_config.go
  go.mod
  go.sum
  protocol/dubbo/client.go
  protocol/dubbo/pool.go
  protocol/dubbo/server.go
Labels: enhancement

#703 Ftr: add dynamic tag router
  before_ut.bat
  before_ut.sh
  cluster/router/chain/chain.go
  cluster/router/chain/chain_test.go
  cluster/router/condition/app_router_test.go
  cluster/router/condition/listenable_router.go
  cluster/router/router.go
  cluster/router/tag/file.go
  cluster/router/tag/router_rule.go
  cluster/router/tag/tag.go
  cluster/router/tag/tag_router.go
  cluster/router/tag/tag_router_test.go
  common/constant/key.go
  go.mod
  go.sum
Labels: enhancement

#694 Fix: Register service instance after provider config load
  common/extension/metadata_service.go
  config/config_loader.go
  config/config_loader_test.go
  config/reference_config_test.go
  config/service_config_test.go
  registry/protocol/protocol.go
  registry/registry_factory.go
  registry/service_discovery_factory.go
  registry/servicediscovery/service_discovery_registry.go
Labels: enhancement, testing

#708 Ftr: bitmap in router chain
  cluster/directory/static_directory.go
  cluster/router/chain.go
  cluster/router/chain/chain.go
  cluster/router/chain/chain_test.go
  cluster/router/chain/invoker_cache.go
  cluster/router/condition/factory_test.go
  cluster/router/condition/listenable_router.go
  cluster/router/condition/router.go
  cluster/router/healthcheck/health_check_route.go
  cluster/router/healthcheck/health_check_route_test.go
  cluster/router/router.go
  cluster/router/tag/file.go
  cluster/router/tag/tag_router.go
  cluster/router/tag/tag_router_test.go
  cluster/router/utils/bitmap_util.go
  common/url.go
  go.mod
  go.sum
  registry/directory/directory.go
Labels: enhancement

#730 Mod: Remove unnecessary return and judgement.
  cluster/router/tag/tag_router.go
  common/rpc_service.go
  common/url.go
  config/base_config.go
  config/reference_config.go
  config_center/configurator/override.go
  protocol/rest/rest_exporter.go
  registry/etcdv3/listener_test.go
  registry/event/service_revision_customizer.go
  registry/protocol/protocol.go
  remoting/zookeeper/curator_discovery/service_discovery.go
Labels: improve
