Repository apache/dubbo-go, pull requests merged in 2020-09, with the labels that each got.

#722 fix exporter append
  common/rpc_service.go
  config/config_loader.go
  config/consumer_config.go
  config/provider_config.go
  config/service_config.go
  metadata/service/exporter/configurable/exporter.go
  protocol/jsonrpc/jsonrpc_protocol.go
  protocol/jsonrpc/server.go
  protocol/protocolwrapper/protocol_filter_wrapper.go
  registry/protocol/protocol.go
  registry/registry.go
Labels: improve

#735 Fix: #734
  remoting/zookeeper/listener.go
Labels: improve

#713 Ftr: [refer dubbo 2.7.6] attachment type from map[string]stiring to map[string]interface{}
  cluster/cluster_impl/zone_aware_cluster_invoker_test.go
  cluster/router/tag/tag_router.go
  common/proxy/proxy.go
  common/proxy/proxy_test.go
  filter/filter_impl/access_log_filter.go
  filter/filter_impl/access_log_filter_test.go
  filter/filter_impl/active_filter_test.go
  filter/filter_impl/auth/default_authenticator_test.go
  filter/filter_impl/auth/provider_auth_test.go
  filter/filter_impl/execute_limit_filter_test.go
  filter/filter_impl/graceful_shutdown_filter_test.go
  filter/filter_impl/metrics_filter_test.go
  filter/filter_impl/seata_filter_test.go
  filter/filter_impl/token_filter.go
  filter/filter_impl/token_filter_test.go
  filter/filter_impl/tps/tps_limiter_method_service_test.go
  filter/filter_impl/tps_limit_filter_test.go
  filter/filter_impl/tracing_filter_test.go
  go.mod
  go.sum
  metadata/service/inmemory/service_proxy.go
  metrics/prometheus/reporter_test.go
  protocol/dubbo/client.go
  protocol/dubbo/client_test.go
  protocol/dubbo/codec.go
  protocol/dubbo/codec_test.go
  protocol/dubbo/dubbo_invoker.go
  protocol/dubbo/dubbo_invoker_test.go
  protocol/dubbo/hessian2/const.go
  protocol/dubbo/hessian2/hessian_dubbo.go
  protocol/dubbo/hessian2/hessian_dubbo_test.go
  protocol/dubbo/hessian2/hessian_request.go
  protocol/dubbo/hessian2/hessian_request_test.go
  protocol/dubbo/hessian2/hessian_response.go
  protocol/dubbo/hessian2/hessian_response_test.go
  protocol/dubbo/listener.go
  protocol/dubbo/listener_test.go
  protocol/dubbo/opentracing.go
  protocol/dubbo/readwriter.go
  protocol/invocation.go
  protocol/invocation/rpcinvocation.go
  protocol/jsonrpc/server.go
  protocol/rest/server/rest_server.go
  protocol/result.go
  test/integrate/dubbo/go-client/go.mod
  test/integrate/dubbo/go-server/go.mod
Labels: enhancement

#740 Fix: integration testing problems
  integrate_test.sh
  test/integrate/dubbo/go-client/Dockerfile
  test/integrate/dubbo/go-client/go.mod
  test/integrate/dubbo/go-server/Dockerfile
  test/integrate/dubbo/go-server/go.mod
Labels: bug

#739 Imp: Improve map access concurrency
  protocol/rpc_status.go
Labels: help wanted, improve

#741 Address notification batch mode
  registry/directory/directory.go
  registry/protocol/protocol.go
  registry/registry.go
Labels: improve

#746 Fix: rename SethealthChecker to SetHealthChecker
  cluster/router/healthcheck/default_health_check.go
  common/extension/health_checker.go
  common/extension/health_checker_test.go
Labels: improve

#747 ProxyInvoker cannot be extended
  common/proxy/proxy_factory/default.go
  registry/protocol/protocol.go
Labels: improve

#738 Fix: add etcdv3 lease to defeat provider register info left in the registry when provider app panic
  registry/etcdv3/registry.go
  remoting/etcdv3/client.go
Labels: improve

#732 Ftr: File system service discovery
  common/constant/key.go
  common/url.go
  config_center/apollo/impl.go
  config_center/base_dynamic_configuration.go
  config_center/dynamic_configuration.go
  config_center/file/factory.go
  config_center/file/impl.go
  config_center/file/impl_test.go
  config_center/file/listener.go
  config_center/mock_dynamic_config.go
  config_center/nacos/impl.go
  config_center/zookeeper/impl.go
  go.mod
  registry/file/listener.go
  registry/file/service_discovery.go
  registry/file/service_discovery_test.go
Labels: enhancement

#701 Ftr: consul service discovery
  common/constant/key.go
  registry/consul/service_discovery.go
  registry/consul/service_discovery_test.go
Labels: enhancement

#754 fix: resove dev RPCResult struct change
  protocol/dubbo/dubbo_codec.go
  protocol/dubbo/impl/codec_test.go
  protocol/dubbo/impl/hessian.go
  protocol/dubbo/impl/request.go
  protocol/dubbo/impl/response.go
  remoting/getty/dubbo_codec_for_test.go
  remoting/getty/listener_test.go
  remoting/getty/opentracing.go
Labels: improve

#673 Rft: network & codec
  .gitignore
  common/constant/default.go
  common/constant/key.go
  common/constant/serializtion.go
  common/url.go
  config/service_config.go
  metadata/service/exporter/configurable/exporter_test.go
  protocol/dubbo/client.go
  protocol/dubbo/client_test.go
  protocol/dubbo/codec.go
  protocol/dubbo/dubbo_codec.go
  protocol/dubbo/dubbo_invoker.go
  protocol/dubbo/dubbo_invoker_test.go
  protocol/dubbo/dubbo_protocol.go
  protocol/dubbo/dubbo_protocol_test.go
  protocol/dubbo/impl/codec.go
  protocol/dubbo/impl/codec_test.go
  protocol/dubbo/impl/const.go
  protocol/dubbo/impl/hessian.go
  protocol/dubbo/impl/package.go
  protocol/dubbo/impl/request.go
  protocol/dubbo/impl/response.go
  protocol/dubbo/impl/serialization.go
  protocol/dubbo/impl/serialize.go
  protocol/dubbo/listener.go
  protocol/dubbo/readwriter.go
  protocol/invocation/rpcinvocation.go
  protocol/jsonrpc/http_test.go
  remoting/codec.go
  remoting/exchange.go
  remoting/exchange_client.go
  remoting/exchange_server.go
  remoting/getty/config.go
  remoting/getty/dubbo_codec_for_test.go
  remoting/getty/getty_client.go
  remoting/getty/getty_client_test.go
  remoting/getty/getty_server.go
  remoting/getty/listener.go
  remoting/getty/listener_test.go
  remoting/getty/opentracing.go
  remoting/getty/pool.go
  remoting/getty/readwriter.go
  test/integrate/dubbo/go-client/go.mod
  test/integrate/dubbo/go-client/go.sum
  test/integrate/dubbo/go-server/go.mod
  test/integrate/dubbo/go-server/go.sum
Labels: enhancement
