Repository apache/dubbo-go, pull requests merged in 2020-11, with the labels that each got.

#831 Ftr:Change verify to Makefile
  .github/workflows/github-actions.yml
  .gitignore
  .travis.yml
  Makefile
  README.md
  README_CN.md
  before_ut.bat
  before_ut.sh
  before_validate_license.sh
Labels: enhancement

#832 Ftr: Add more automatic components
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#824 Ftr: Add grpc max message size config
  common/constant/key.go
  config/service_config.go
  protocol/grpc/client.go
  protocol/grpc/grpc_protocol.go
  protocol/grpc/server.go
Labels: enhancement

#856 Update readme user list
  README_CN.md
Labels: good first issue

#797 Imp: try to fix too many files open error
  common/url.go
  go.mod
  go.sum
  protocol/dubbo/client.go
  protocol/dubbo/config.go
  protocol/dubbo/dubbo_invoker.go
  protocol/dubbo/pool.go
Labels: good first issue, improve

#878 Fix:github.com/shirou/gopsutil can not compile in darwin
  go.mod
  go.sum
Labels: bug

#883 Ftr: Add release notes
  CHANGE.md
  README.md
  README_CN.md
Labels: enhancement
