Repository apache/dubbo-go, pull requests merged in 2021-12, with the labels that each got.

#1626 add:support file extension
  config/config_center_config.go
  config/config_loader_options.go
  config/config_loader_options_test.go
Labels: feature

#1630 FIX:Array boundary problem
  common/file/suffix.go
  config/config_loader_options.go
  config/config_loader_options_test.go
  config/config_resolver.go
Labels: bug

#1547 Opt: upgrade dubbo-getty from 1.4.5 to 1.4.7-rc2
  go.mod
  go.sum
Labels: do not merge
